config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"

  resources :cocktail do
    resources :dose, only: [:new, :create, :destroy]
  end

  root to: 'cocktail#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  has_attachments :photos, maximum: 5

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates_uniqueness_of :cocktail_id, :scope => :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktail_controller.rb
class CocktailController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      flash[:notice] = "New cocktail successfully created !!"
      redirect_to cocktail_path(@cocktail.id)
    else
      flash[:notice] = "Oops something went wrong !!"
      render "new"
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, photos: [])
  end
end

app/controllers/dose_controller.rb
class DoseController < ApplicationController
  before_action :find_cocktail, only: [:new, :create, :destroy]

  def new
    @dose = Dose.new
  end

  def create
    @dose = @cocktail.doses.build(dose_params)
    #does the same thing as :
    # @dose = Dose.new
    # @dose.cocktail = @cocktail
    # @dose.save

    if @dose.save
      flash[:notice] = "New cocktail successfully created !!"
      redirect_to cocktail_path(@cocktail.id)
    else
      flash[:notice] = "Oops something went wrong !!"
      render "new"
    end
  end

  def destroy
    @dose = @cocktail.doses.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail.id)
  end

private

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/views/cocktail/edit.html.erb
<h1>Cocktail#edit</h1>
<p>Find me in app/views/cocktail/edit.html.erb</p>

app/views/cocktail/index.html.erb
<div class="container">
  <div class="text-center">

    <% if @cocktails.empty? %>
      <p>You have no Cocktails yet. Why not <%= link_to 'Add a new one', new_cocktail_path %> ?</p>
    <% else %>
      <div class="row">
        <% @cocktails.each do |cocktail| %>
          <div class="col-sm-8 col-sm-offset-2">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cloudinary_url cocktail.photos.first.path %>');">
              <div class="card-category">Popular</div>
              <div class="card-description">
                <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
                <p><%= link_to 'Add dose', new_cocktail_dose_path(cocktail) %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="row">
      <p><%= link_to 'Add new cocktail', new_cocktail_path %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktail/new.html.erb
<div class="container">
  <div class="text-center">
    <h1>Create a new Cocktail !</h1>

    <%= simple_form_for @cocktail, :url => cocktail_index_path do |f| %>
      <%= f.input :name %>
      <%= f.input :photos, as: :attachinary %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>


<%= link_to "Back", cocktail_index_path %>

app/views/cocktail/show.html.erb
<div class="container">
  <div class="text-center">
    <h1>Cocktail#show</h1>
    <p>Find me in app/views/cocktail/show.html.erb</p>

    <% @cocktail.photos.each do |photo| %>
      <%= cl_image_tag photo.path, width: 300, height: 200, crop: :fill %>
    <% end %>

    <h3>Ingredients :</h3>

    <% @cocktail.doses.each do |dose| %>
      <ul class="list-unstyled">
        <li><%= dose.description + " of " %> <%= dose.ingredient.name %> <%=link_to "Delete dose", cocktail_dose_path(@cocktail, dose), method: :delete %></li>
      </ul>
    <% end %>

    <p><%= link_to "Add dose", new_cocktail_dose_path(@cocktail) %></p>

    <!-- attention: because the destroy is also nested, I had to pass two params to the route DELETE:
    - the cocktail ID and the dose ID
  -->

  <p><%= link_to "Back", root_path%></p>
</div>
</div>

app/views/dose/new.html.erb
<div class="container">
  <div class="text-center">
    <h1>Doses#new</h1>
    <p>Find me in app/views/doses/new.html.erb</p>

    <%= form_for [@cocktail, @dose], url: cocktail_dose_index_path(@cocktail) do |f| %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.label :ingredient %>
    <%= f.collection_select :ingredient_id, Ingredient.all, :id, :name %>
    <%= f.submit 'Submit' %>
    <% end %>

    <p><%= link_to "Back", cocktail_path(@cocktail) %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= cloudinary_js_config %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

<body>
  <%= yield %>
</body>
</html>